"""
RRM Media Client — 4-Month Engagement Template
32 tasks across 7 phases, mapped from RRM SOPs.
"""

RRM_MEDIA_CLIENT_TEMPLATE = {
    "id": "rrm-media-client-template-v1",
    "is_global": True,
    "org_id": None,
    "name": "RRM Media Client — 4-Month Engagement",
    "description": "Full delivery flow for Canadian realtor clients. Covers kickoff through renewal.",
    "offer_type": "rrm_media_client",
    "type": "engagement",
    "trigger": "rrm_media_client",
    "icon": "🤝",
    "phases": ["Kickoff & Onboarding", "Build", "Launch", "Month 1", "Month 2", "Month 3", "Month 4 & Renewal"],
    "tasks": [
        # ── PHASE: Kickoff & Onboarding (Day 0–5) ──
        {"title": "Send Welcome Email", "phase": "Kickoff & Onboarding", "day_offset": 0, "assignee_role": "account_manager", "sop_reference": "SOP 01 — Welcome Email", "is_client_visible": False, "checklist": ["Replace all [PLACEHOLDERS]", "Add GHL onboarding form link", "Add WhatsApp group"]},
        {"title": "Send Onboarding Instructions", "phase": "Kickoff & Onboarding", "day_offset": 0, "assignee_role": "account_manager", "sop_reference": "SOP 02 — Client Onboarding Instructions", "checklist": ["Send doc via email or WhatsApp"]},
        {"title": "Send FAQ Doc", "phase": "Kickoff & Onboarding", "day_offset": 0, "assignee_role": "account_manager", "sop_reference": "SOP 03 — FAQ", "checklist": ["Send FAQ to client WhatsApp group"]},
        {"title": "Create WhatsApp Group", "phase": "Kickoff & Onboarding", "day_offset": 0, "assignee_role": "account_manager", "checklist": ["Add client", "Add Vitto", "Add Lucca", "Pin onboarding instructions"]},
        {"title": "Confirm Contract Signed + Payment Received", "phase": "Kickoff & Onboarding", "day_offset": 0, "assignee_role": "account_manager", "sop_reference": "SOP 30 — Contract & Payment Setup", "checklist": ["Contract signed", "PIF confirmed ($3,500)", "Move to Closed Won in GHL", "GHL automation fires"]},
        {"title": "Schedule & Complete Kickoff Call (KOM)", "phase": "Kickoff & Onboarding", "day_offset": 2, "assignee_role": "account_manager", "sop_reference": "SOP 05 — Kickoff Call (A.L.I.G.N.)", "is_client_visible": True, "checklist": ["Review sales notes before call", "A — Acknowledge: reference why they bought", "L — Lock Pain: confirm core problem", "I — Identify Outcome: define measurable success", "G — Gather Inputs: collect all missing assets", "N — Next Steps: confirm build path", "Post-call: send WhatsApp recap", "Post-call: assign build tasks to Lucca", "Post-call: update client record"]},
        {"title": "Collect All Client Assets", "phase": "Kickoff & Onboarding", "day_offset": 3, "assignee_role": "account_manager", "is_client_visible": True, "checklist": ["Professional headshot", "Brokerage logo (PNG transparent)", "Bio / About text (first person, 2 paragraphs)", "Brokerage branding guidelines", "Facebook Page admin access", "Meta Business Manager / Ad Account partner access", "Google Calendar booking link", "Testimonials or proof assets", "Thank-you page video filmed (or script sent)"]},

        # ── PHASE: Build (Day 5–12) ──
        {"title": "GHL Sub-Account Setup", "phase": "Build", "day_offset": 5, "assignee_role": "operator", "sop_reference": "SOP 10 — GHL Build (16-Step)", "checklist": ["Create sub-account", "Apply client branding", "Install Meta Pixel", "Load client assets (logo, headshot, bio)", "Configure 5 automations (Speed-to-Lead, nurture, long-term follow-up)", "Configure Google Calendar booking integration", "QA all automations", "Record Loom walkthrough for client"]},
        {"title": "Build Landing Page", "phase": "Build", "day_offset": 5, "assignee_role": "operator", "sop_reference": "SOP 12 — Landing Page Build", "checklist": ["Hero section with matching headline", "Trust section (testimonials if available)", "Value proposition (3-5 bullets)", "About agent section", "Lead form: Name, Email, Phone + 4-question survey", "Thank-you page with video (or fallback image)", "Calendar widget on thank-you page", "Brokerage logo visible (Canadian legal requirement)", "Mobile-first design confirmed", "Domain + DNS configured"]},
        {"title": "Build Meta Campaign", "phase": "Build", "day_offset": 7, "assignee_role": "operator", "sop_reference": "SOP 11 — Meta Campaign Setup", "checklist": ["Campaign objective: Leads", "Housing category ON (required in Canada)", "4 ad sets × $7.50 = $30/day minimum", "Instant form: Higher Intent, 4 survey questions", "6+ creative angles prepared (from SOP 06)", "UTM parameters configured", "Pixel events verified firing", "CASL-compliant copy (brokerage logo in creative)"]},
        {"title": "Pre-Launch QA", "phase": "Build", "day_offset": 10, "assignee_role": "operator", "checklist": ["Test lead form submission end-to-end", "Confirm lead lands in GHL CRM", "Confirm Speed-to-Lead SMS fires within 5 min", "Confirm booking link works", "Confirm thank-you page loads with video", "Confirm all ad sets approved by Meta"]},

        # ── PHASE: Launch (Day 12–14) ──
        {"title": "Complete Launch Call", "phase": "Launch", "day_offset": 12, "assignee_role": "account_manager", "sop_reference": "SOP 09 — Launch Call", "is_client_visible": True, "checklist": ["Set expectations BEFORE showing ads", "Explain testing phase (no panic in first 2 weeks)", "Re-anchor real goal: booked appointments, not just leads", "Explain client role (answer calls, follow up, be present)", "Explain communication cadence (bi-weekly calls, WhatsApp updates)", "Walk through the full campaign", "Get launch approval", "Collect any final revisions"]},
        {"title": "Go Live — Activate Campaign", "phase": "Launch", "day_offset": 14, "assignee_role": "operator", "checklist": ["Turn on all ad sets", "Monitor at 30 min post-launch", "Monitor at 4 hours post-launch", "Monitor at 24 hours post-launch", "Monitor at 48 hours post-launch", "Activate ISA", "Notify client in WhatsApp: campaign is live"]},

        # ── PHASE: Month 1 ──
        {"title": "Week 1 — Monitor Only (No Changes)", "phase": "Month 1", "day_offset": 14, "assignee_role": "operator", "sop_reference": "SOP 13 — Go-Live Weeks 1-4", "checklist": ["Daily health check", "Log all metrics", "Do NOT make changes", "Check speed-to-lead daily"]},
        {"title": "Week 2 — First Data Review", "phase": "Month 1", "day_offset": 21, "assignee_role": "operator", "sop_reference": "SOP 13 — Go-Live Weeks 1-4", "checklist": ["Run Green/Yellow/Red assessment", "Identify optimization priority", "Log decision in client tracker"]},
        {"title": "Bi-Weekly Check-In Call #1", "phase": "Month 1", "day_offset": 21, "assignee_role": "account_manager", "sop_reference": "SOP 15 — Client Check-In Call", "is_client_visible": True, "checklist": ["Review tracker pre-call", "Check health score (1-30 scale)", "Lead with positives", "Share what's working + what's adjusting", "Confirm next steps", "Log churn risk signals if any"]},
        {"title": "Week 3 — Optimize Based on Status", "phase": "Month 1", "day_offset": 28, "assignee_role": "operator", "sop_reference": "SOP 14 — D.A.T.A. Optimization", "checklist": ["Diagnose bottleneck layer", "Make one high-leverage change", "Log change + reason", "Alert client if relevant"]},
        {"title": "Bi-Weekly Check-In Call #2", "phase": "Month 1", "day_offset": 35, "assignee_role": "account_manager", "sop_reference": "SOP 15 — Client Check-In Call", "is_client_visible": True, "checklist": ["Pre-call review", "Performance update", "Next steps"]},
        {"title": "Month 1 Performance Report", "phase": "Month 1", "day_offset": 42, "assignee_role": "account_manager", "sop_reference": "SOP 16 — Client Reporting Template", "is_client_visible": True, "checklist": ["Total spend", "Total leads", "CPL", "Booked appointments", "Show rate", "What worked", "What we're improving", "Next month plan"]},

        # ── PHASE: Month 2 ──
        {"title": "Bi-Weekly Check-In Call #3", "phase": "Month 2", "day_offset": 49, "assignee_role": "account_manager", "sop_reference": "SOP 15 — Client Check-In Call", "is_client_visible": True, "checklist": ["Pre-call review", "Performance update", "Collect early testimonial if results exist"]},
        {"title": "Creative Refresh Review", "phase": "Month 2", "day_offset": 56, "assignee_role": "operator", "sop_reference": "SOP 24 — Creative Refresh (70/20/10)", "checklist": ["Classify all creatives: Winner / Promising / Underperforming / Dead", "70% budget → winner variations", "20% → new variations of proven angles", "10% → completely new angles", "Check frequency (pause if >3.0)", "Check CTR decline + CPL increase"]},
        {"title": "Bi-Weekly Check-In Call #4", "phase": "Month 2", "day_offset": 63, "assignee_role": "account_manager", "sop_reference": "SOP 15 — Client Check-In Call", "is_client_visible": True, "checklist": ["Pre-call review", "Performance update", "Next steps"]},
        {"title": "Month 2 Performance Report", "phase": "Month 2", "day_offset": 72, "assignee_role": "account_manager", "sop_reference": "SOP 16 — Client Reporting Template", "is_client_visible": True, "checklist": ["Full report + Month 3 plan"]},
        {"title": "Request Testimonial", "phase": "Month 2", "day_offset": 72, "assignee_role": "account_manager", "sop_reference": "SOP 26 — Testimonial & Case Study", "checklist": ["Screenshot proof", "Written 2-3 sentences", "Video testimonial (optional, 60 sec)"]},

        # ── PHASE: Month 3 ──
        {"title": "Bi-Weekly Check-In Call #5", "phase": "Month 3", "day_offset": 77, "assignee_role": "account_manager", "sop_reference": "SOP 15 — Client Check-In Call", "is_client_visible": True, "checklist": ["Pre-call review", "Performance update", "Begin renewal prep internally"]},
        {"title": "Second Creative Refresh", "phase": "Month 3", "day_offset": 84, "assignee_role": "operator", "sop_reference": "SOP 24 — Creative Refresh (70/20/10)", "checklist": ["Re-classify all creatives", "Refresh 70/20/10", "New angles based on Month 2 data"]},
        {"title": "Bi-Weekly Check-In Call #6", "phase": "Month 3", "day_offset": 91, "assignee_role": "account_manager", "sop_reference": "SOP 15 — Client Check-In Call", "is_client_visible": True, "checklist": ["Pre-call review", "Discuss renewal options informally"]},
        {"title": "Month 3 Performance Report", "phase": "Month 3", "day_offset": 100, "assignee_role": "account_manager", "sop_reference": "SOP 16 — Client Reporting Template", "is_client_visible": True, "checklist": ["Full report + Month 4 plan + renewal context"]},

        # ── PHASE: Month 4 & Renewal ──
        {"title": "Schedule Renewal Call (R.E.N.E.W.)", "phase": "Month 4 & Renewal", "day_offset": 105, "assignee_role": "account_manager", "sop_reference": "SOP 17 — SCP Renewal Call", "checklist": ["Send pre-call email asking what felt valuable", "Ask what to improve", "Ask for specific concerns"]},
        {"title": "Complete Renewal Call", "phase": "Month 4 & Renewal", "day_offset": 110, "assignee_role": "account_manager", "sop_reference": "SOP 17 — R.E.N.E.W. Framework", "is_client_visible": True, "checklist": ["R — Review: what happened over 4 months", "E — Expose Gap: what's left to solve", "N — Next Plan: present 3 options", "E — Enroll or Exit: get the decision", "W — Wrap: lock next steps", "Log decision in CRM"]},
        {"title": "Month 4 Final Report", "phase": "Month 4 & Renewal", "day_offset": 118, "assignee_role": "account_manager", "sop_reference": "SOP 16 — Client Reporting Template", "is_client_visible": True, "checklist": ["Final performance summary", "ROI summary", "Renewal or offboarding path confirmed"]},
        {"title": "Collect Case Study", "phase": "Month 4 & Renewal", "day_offset": 118, "assignee_role": "account_manager", "sop_reference": "SOP 26 — Testimonial & Case Study", "checklist": ["Client profile + problem", "Solution summary", "Results with numbers", "Client quote", "Video testimonial"]},
        {"title": "Offboarding (if not renewing)", "phase": "Month 4 & Renewal", "day_offset": 120, "assignee_role": "account_manager", "sop_reference": "SOP 25 — Client Offboarding", "checklist": ["Deliver final performance summary", "Transfer Meta ad account assets", "Transfer GHL sub-account", "Export all lead data to client", "Remove RRM partner access", "Conduct exit interview (5 questions)", "Request testimonial/referral", "Schedule 30/60/90-day nurture check-ins", "Internal debrief: log churn reason"]},
    ]
}

# ── Campaign: Launch Meta Campaign ──
CAMPAIGN_LAUNCH_TEMPLATE = {
    "id": "rrm-campaign-launch-v1", "is_global": True, "org_id": None,
    "name": "Launch Meta Campaign", "description": "Full campaign build from angle selection through go-live.",
    "offer_type": None, "type": "campaign", "trigger": None, "icon": "📣",
    "phases": ["Strategy", "Creative", "Build", "QA & Launch"],
    "tasks": [
        {"title": "Select campaign angle", "phase": "Strategy", "day_offset": 0, "sop_reference": "SOP 32 — Campaign Strategy Playbook", "checklist": ["Seller's Guide", "Free Home Eval", "Buyer's Guide", "Downsizing", "Upsizing", "Divorce", "Expired Listing", "Home Equity", "GST Rebate", "Investor", "Relocation", "Retargeting"]},
        {"title": "Write ad copy (3 variations)", "phase": "Creative", "day_offset": 1, "sop_reference": "SOP 06 — Ad Copy Templates", "checklist": ["Headline variation 1", "Headline variation 2", "Headline variation 3", "Body copy", "CTA", "CASL compliant"]},
        {"title": "Write VSL / thank-you page script", "phase": "Creative", "day_offset": 1, "sop_reference": "SOP 04 — Thank You Page VSL Scripts", "checklist": ["Select correct script angle", "Customize with agent name + market", "Send to client for filming"]},
        {"title": "Prepare 6+ creative assets", "phase": "Creative", "day_offset": 2, "sop_reference": "SOP 24 — Creative Refresh (70/20/10)", "checklist": ["6 angles minimum", "5 hooks per angle", "Static images", "Video creatives", "Brokerage logo on all"]},
        {"title": "Build landing page", "phase": "Build", "day_offset": 2, "sop_reference": "SOP 12 — Landing Page Build", "checklist": ["Hero + matching headline", "Value proposition", "Lead form", "Thank-you page with video + calendar", "Mobile-first", "Brokerage logo visible"]},
        {"title": "Build Meta campaign in Ads Manager", "phase": "Build", "day_offset": 3, "sop_reference": "SOP 11 — Meta Campaign Setup", "checklist": ["Leads objective", "Housing category ON", "4 ad sets × $7.50", "Higher Intent form", "Pixel events firing", "UTMs configured"]},
        {"title": "Configure GHL lead flow", "phase": "Build", "day_offset": 3, "checklist": ["Lead form → GHL webhook", "Speed-to-Lead SMS", "CRM pipeline stage", "ISA notified"]},
        {"title": "QA end-to-end", "phase": "QA & Launch", "day_offset": 4, "checklist": ["Submit test lead", "Confirm CRM entry", "Confirm SMS fires", "Confirm booking link works", "All ads approved"]},
        {"title": "Go live + monitor", "phase": "QA & Launch", "day_offset": 5, "checklist": ["Turn on campaign", "Monitor at 30 min", "Monitor at 4 hours", "Monitor at 24 hours", "Notify client"]},
    ]
}

# ── Funnel: Build VSL Funnel ──
VSL_FUNNEL_TEMPLATE = {
    "id": "rrm-vsl-funnel-v1", "is_global": True, "org_id": None,
    "name": "Build VSL Funnel", "description": "Script, build, and launch a video sales letter funnel end-to-end.",
    "offer_type": None, "type": "funnel", "trigger": None, "icon": "🎬",
    "phases": ["Script", "Assets", "Page Build", "Automation", "Launch"],
    "tasks": [
        {"title": "Write VSL script", "phase": "Script", "day_offset": 0, "sop_reference": "SOP 04 — Thank You Page VSL Scripts", "checklist": ["Hook (first 10 sec)", "Problem + agitation", "Solution reveal", "Proof/credibility", "Offer presentation", "CTA", "Under 90 seconds"]},
        {"title": "Film VSL", "phase": "Assets", "day_offset": 1, "checklist": ["Landscape mode", "Natural light", "Clean background", "Quiet room", "Speak naturally", "Upload to Drive"]},
        {"title": "Edit + caption video", "phase": "Assets", "day_offset": 2, "checklist": ["Trim start/end", "Add captions", "Add branding overlay", "Add CTA overlay", "Export MP4 under 50MB"]},
        {"title": "Build opt-in page", "phase": "Page Build", "day_offset": 2, "checklist": ["Headline matches ad promise", "Lead form", "Trust indicators", "Mobile-first"]},
        {"title": "Build thank-you / VSL page", "phase": "Page Build", "day_offset": 3, "checklist": ["VSL video embedded", "Calendar widget below", "CTA clear"]},
        {"title": "Set up automation sequence", "phase": "Automation", "day_offset": 3, "checklist": ["SMS confirmation", "Speed-to-Lead", "Email follow-up (Day 1, 3, 7)", "CRM pipeline stage"]},
        {"title": "Test + go live", "phase": "Launch", "day_offset": 4, "checklist": ["Submit test lead", "Watch full automation fire", "Confirm booking link", "Connect to ad traffic"]},
    ]
}

# ── Process: Monthly Creative Refresh ──
CREATIVE_REFRESH_TEMPLATE = {
    "id": "rrm-creative-refresh-v1", "is_global": True, "org_id": None,
    "name": "Monthly Creative Refresh", "description": "Audit, classify, and refresh ad creatives every 2-4 weeks.",
    "offer_type": None, "type": "process", "trigger": None, "icon": "🔄",
    "phases": ["Audit", "Classify", "Create", "Deploy"],
    "tasks": [
        {"title": "Pull performance data (last 14 days)", "phase": "Audit", "day_offset": 0, "sop_reference": "SOP 24 — Creative Refresh (70/20/10)", "checklist": ["CTR per creative", "CPL per creative", "Frequency (flag if >3.0)", "Hook hold rate", "Negative sentiment"]},
        {"title": "Classify all creatives", "phase": "Classify", "day_offset": 0, "checklist": ["🟢 Winner — scale", "🟡 Promising — test more", "🔴 Underperforming — pause", "⚫ Dead — archive"]},
        {"title": "Plan new creatives (70/20/10)", "phase": "Create", "day_offset": 1, "checklist": ["70% — winner variations", "20% — promising variations", "10% — new angles", "Minimum 6 new assets"]},
        {"title": "Write new ad copy", "phase": "Create", "day_offset": 1, "sop_reference": "SOP 06 — Ad Copy Templates"},
        {"title": "Produce creative assets", "phase": "Create", "day_offset": 2, "checklist": ["Static images (3+)", "Video creatives (2+)", "CASL-compliant"]},
        {"title": "Deploy + pause dead creatives", "phase": "Deploy", "day_offset": 3, "checklist": ["Upload to Ads Manager", "Add to correct ad sets", "Pause all Dead creatives", "Log changes", "Notify client"]},
    ]
}

# ── Internal: Warm Outreach Sprint ──
OUTREACH_SPRINT_TEMPLATE = {
    "id": "rrm-warm-outreach-v1", "is_global": True, "org_id": None,
    "name": "Warm Outreach Sprint (1 Week)", "description": "Daily outreach targeting Canadian realtors. 100 IG DMs + 20 LinkedIn DMs per day.",
    "offer_type": None, "type": "internal", "trigger": None, "icon": "📲",
    "phases": ["Setup", "Execution", "Review"],
    "tasks": [
        {"title": "Build prospect list (500+ minimum)", "phase": "Setup", "day_offset": 0, "sop_reference": "SOP 20 — Warm Outreach", "checklist": ["Realtor.ca + Instant Data Scraper", "ICP: Canadian agents, 10-30 deals/year", "Filter: active listings, local market", "Export to spreadsheet"]},
        {"title": "Prepare DM templates (IG + LinkedIn)", "phase": "Setup", "day_offset": 0, "checklist": ["IG DM: question-based, not pitch", "LinkedIn DM: professional tone", "Follow-up template ready", "Break-up message ready"]},
        {"title": "Day 1 outreach", "phase": "Execution", "day_offset": 1, "checklist": ["100 IG follow requests", "100 IG DMs to accepted follows", "20 LinkedIn connections", "20 LinkedIn DMs", "Replies logged", "Calls noted in CRM"]},
        {"title": "Day 2 outreach", "phase": "Execution", "day_offset": 2, "checklist": ["100 IG follow requests", "100 IG DMs", "20 LinkedIn connections", "20 LinkedIn DMs", "Replies logged"]},
        {"title": "Day 3 outreach", "phase": "Execution", "day_offset": 3, "checklist": ["100 IG follow requests", "100 IG DMs", "20 LinkedIn connections", "20 LinkedIn DMs", "Replies logged"]},
        {"title": "Day 4 outreach", "phase": "Execution", "day_offset": 4, "checklist": ["100 IG follow requests", "100 IG DMs", "20 LinkedIn connections", "20 LinkedIn DMs", "Replies logged"]},
        {"title": "Day 5 outreach", "phase": "Execution", "day_offset": 5, "checklist": ["100 IG follow requests", "100 IG DMs", "20 LinkedIn connections", "20 LinkedIn DMs", "Replies logged"]},
        {"title": "Sprint review", "phase": "Review", "day_offset": 6, "checklist": ["Total DMs sent", "Reply rate", "Calls booked", "Conversion to closed", "Adjust messaging"]},
    ]
}

# ── Internal: ISA Hire + Onboard ──
ISA_HIRE_TEMPLATE = {
    "id": "rrm-isa-hire-v1", "is_global": True, "org_id": None,
    "name": "Hire & Train ISA", "description": "Full hiring and training flow for an Inside Sales Agent via OnlineJobs.ph.",
    "offer_type": None, "type": "internal", "trigger": None, "icon": "🧑‍💼",
    "phases": ["Sourcing", "Interviews", "Hire", "Training", "Go Live"],
    "tasks": [
        {"title": "Post job on OnlineJobs.ph", "phase": "Sourcing", "day_offset": 0, "sop_reference": "SOP 28 — ISA Hiring & Training", "checklist": ["Title: Inside Sales Agent (Inbound Leads)", "NOT cold calling", "Rate: $4-8 USD/hr", "Required: excellent English, quiet workspace", "Include voice note test"]},
        {"title": "Review applications + voice notes", "phase": "Interviews", "day_offset": 3, "checklist": ["Filter by English clarity", "Filter by energy and tone", "Shortlist top 5"]},
        {"title": "Round 1: 15-min live call", "phase": "Interviews", "day_offset": 5, "checklist": ["Assess communication style", "Confirm availability (11AM-8PM EST)", "Confirm tech setup"]},
        {"title": "Round 2: Role play (10-min)", "phase": "Interviews", "day_offset": 6, "sop_reference": "SOP 08 — ISA Scripts", "checklist": ["Use buyer script", "Assess objection handling", "Score: tone, script adherence, confidence"]},
        {"title": "Extend offer + confirm start", "phase": "Hire", "day_offset": 7},
        {"title": "Training Day 1-2: Context + Systems", "phase": "Training", "day_offset": 8, "sop_reference": "SOP 08 — ISA Scripts & Workflow", "checklist": ["Walk through RRM offer + client journey", "GHL CRM walkthrough", "Pipeline stages explained", "Speed-to-Lead rule: 5 minutes"]},
        {"title": "Training Day 3-4: Script practice", "phase": "Training", "day_offset": 10, "checklist": ["Buyer script", "Seller script", "Voicemail script", "Objection handling", "Role play with team"]},
        {"title": "Training Day 5: Supervised live calls", "phase": "Training", "day_offset": 12, "checklist": ["Listen to 10 live calls", "Debrief after each", "Sign off on performance"]},
        {"title": "ISA go live independently", "phase": "Go Live", "day_offset": 14, "checklist": ["Daily schedule: 11AM-8PM EST", "Daily report format sent", "QA: review 5 random calls/week", "First week check-in booked"]},
    ]
}

# ── YouTube Video — Internal RRM Production Pipeline ──
YOUTUBE_VIDEO_TEMPLATE = {
    "id": "rrm-youtube-video-production-v1",
    "is_global": True,
    "org_id": None,
    "name": "YouTube Video — Full Production Pipeline",
    "description": "End-to-end production flow for a single YouTube long-form video. Covers scripting through 30-day analytics. Generates 7 shorts, 1 highlight reel, 3 stories, and a full publishing run via Descript and Nextcloud.",
    "offer_type": None,
    "type": "content",
    "trigger": None,
    "icon": "\U0001f3ac",
    "phases": [
        "Pre-Production",
        "Production",
        "Post-Production",
        "Repurposing",
        "Publishing Prep",
        "Distribution",
        "Analytics"
    ],
    "tasks": [
        # ── PHASE: Pre-Production (Day 0–3) ──
        {"title": "Write Video Script", "phase": "Pre-Production", "day_offset": 0, "assignee_role": "operator", "description": "Write the full script for the video. Include hook, body, and CTA. CTA should point to VSL funnel or lead magnet first.", "checklist": ["Define the core topic and angle", "Write hook (first 30 seconds — pattern interrupt)", "Write body (main content, story, or framework)", "Write CTA — primary: VSL funnel. Secondary: lead magnet", "Keep long-form under 15 min for retention", "Format in Google Doc with scene/b-roll notes", "Share doc link in this task's comments"]},
        {"title": "Script Review & Approval", "phase": "Pre-Production", "day_offset": 1, "assignee_role": "account_manager", "is_client_visible": False, "description": "Vitto reviews the script. Approve or request revisions. Must be approved before filming.", "checklist": ["Read full script", "Check hook — would you stop scrolling?", "Check CTA alignment — VSL funnel or lead magnet first", "Check messaging consistency with RRM positioning", "Approve or leave revision comments in Google Doc", "Mark this task done only when approved"]},
        {"title": "Script Revisions (if needed)", "phase": "Pre-Production", "day_offset": 2, "assignee_role": "operator", "description": "Apply all revision notes from Vitto. Only needed if revisions were requested.", "checklist": ["Address all comments in Google Doc", "Re-share updated script", "Confirm with Vitto before moving to filming"]},
        {"title": "Create Slide Assets (if needed)", "phase": "Pre-Production", "day_offset": 2, "assignee_role": "operator", "description": "Create any supporting slide assets, graphics, or on-screen visuals needed for the video. Skip if not applicable.", "checklist": ["Identify which script sections need visual support", "Build slides in Canva (use RRM brand: red #A2182C, gold #97662D, teal #AEC6C8)", "Export as PNG or PDF", "Upload to Nextcloud: ops.redribbongroup.ca", "Share Nextcloud link in task comments", "Mark N/A in comments if no slides needed"]},
        {"title": "Filming Day Prep", "phase": "Pre-Production", "day_offset": 2, "assignee_role": "operator", "description": "Prepare everything needed for filming day. Confirm with Vitto 24 hours before.", "checklist": ["Script printed or on teleprompter/iPad", "Location confirmed (clean background, good lighting)", "Camera setup confirmed (landscape, stable)", "Audio confirmed (lapel mic or quiet room)", "Lighting confirmed (natural light or ring light)", "All assets/slides ready to display if needed", "Confirm filming date with Vitto"]},

        # ── PHASE: Production (Day 3–4) ──
        {"title": "Film the Video", "phase": "Production", "day_offset": 3, "assignee_role": "account_manager", "description": "Vitto films the video. Lucca coordinates. Aim for 1-3 takes per section.", "checklist": ["Record in landscape (4K or 1080p minimum)", "Film intro/hook as its own take", "Film each main section separately for easier editing", "Film CTA segment last", "Film b-roll if applicable (screen recordings, walkthrough shots)", "Review footage before wrapping — check audio sync", "Do not delete any takes"]},
        {"title": "Upload Raw Footage to NAS", "phase": "Production", "day_offset": 3, "assignee_role": "operator", "description": "Transfer all raw footage to TrueNAS storage immediately after filming.", "checklist": ["Create a new folder: /videos/YYYY-MM-DD_[video-title]/raw/", "Upload all camera files, screen recordings, and b-roll", "Verify file count matches what was filmed", "Do not rename files — keep original camera names", "Confirm upload complete before proceeding"]},
        {"title": "Scan NAS & Get Nextcloud Share Link", "phase": "Production", "day_offset": 4, "assignee_role": "operator", "description": "Use web SSH to run the NAS scan procedure, then generate a Nextcloud share link for the editor.", "checklist": ["Open TrueNAS web SSH at your NAS IP", "Run scan procedure to index new files", "Navigate to Nextcloud: https://ops.redribbongroup.ca/login?redirect_url=/apps/dashboard/", "Log in to Nextcloud", "Locate the raw footage folder", "Right-click folder → Share → Create share link", "Set expiry if needed (14 days minimum)", "Copy the share link", "Paste Nextcloud share link in this task's comments"]},

        # ── PHASE: Post-Production (Day 4–12) ──
        {"title": "Send Editor Brief", "phase": "Post-Production", "day_offset": 4, "assignee_role": "operator", "description": "Package and send everything the editor needs to start cutting.", "checklist": ["Send Nextcloud raw footage link", "Send Google Doc script link", "Send slide assets link (if applicable)", "Specify format: landscape 16:9, export MP4 H.264", "Specify style: jump cuts, captions optional at this stage, pacing to match script", "Specify CTA placement: last 30 seconds of video", "Set deadline: confirm with editor", "Send via Conversations thread or WhatsApp"]},
        {"title": "Edit Long-Form Video", "phase": "Post-Production", "day_offset": 5, "assignee_role": "editor", "description": "Editor cuts the full long-form video from raw footage using the script and assets provided.", "checklist": ["Import all raw footage from Nextcloud link", "Cut to script — remove flubs, long pauses, repeated takes", "Add b-roll where script notes indicate", "Add slide assets at correct timestamps", "Add lower thirds if applicable (name, title)", "Colour grade to match RRM aesthetic", "Add background music (royalty-free, low volume)", "Add captions (auto-generate then review for accuracy)", "Export MP4 — 1080p minimum, H.264", "Upload export to Nextcloud: /videos/YYYY-MM-DD_[video-title]/edit-v1/", "Share Nextcloud link in task comments"]},
        {"title": "First Review", "phase": "Post-Production", "day_offset": 8, "assignee_role": "account_manager", "is_client_visible": False, "description": "Vitto watches the full edit and logs all revision notes. Be specific — timestamp every note.", "checklist": ["Watch full video from Nextcloud link", "Check hook — does it grab attention in first 5 seconds?", "Check pacing — no dead air, no rushed sections", "Check b-roll sync to script", "Check captions for accuracy", "Check CTA — clear and on-screen long enough", "Log all notes with timestamps in task comments", "Approve OR request revisions"]},
        {"title": "Revision Round 1 (if needed)", "phase": "Post-Production", "day_offset": 9, "assignee_role": "editor", "description": "Apply all revision notes from first review. Export as v2.", "checklist": ["Address every timestamped note", "Export as edit-v2", "Upload to Nextcloud: /videos/YYYY-MM-DD_[video-title]/edit-v2/", "Share updated link in task comments"]},
        {"title": "Second Review & Final Acceptance", "phase": "Post-Production", "day_offset": 10, "assignee_role": "account_manager", "is_client_visible": False, "description": "Final sign-off on the long-form edit. Once accepted, proceed to repurposing.", "checklist": ["Watch full v2 edit", "Confirm all revision notes addressed", "If minor issues remain: log and operator handles", "Accept the edit — mark done", "Notify operator to proceed to Descript"]},

        # ── PHASE: Repurposing (Day 10–13) ──
        {"title": "Export 7 Shorts via Descript", "phase": "Repurposing", "day_offset": 10, "assignee_role": "operator", "description": "Use Descript to clip and export 7 short-form videos from the approved long-form edit.", "checklist": ["Import approved long-form edit into Descript", "Identify 7 high-value clips (hook moments, key insights, quotable lines)", "Each short: 30–90 seconds, vertical 9:16 format", "Add animated captions in Descript (match brand style)", "Add RRM logo watermark if applicable", "Export all 7 as MP4 — vertical, 1080x1920", "Name files: short-01.mp4 through short-07.mp4", "Upload to Nextcloud: /videos/YYYY-MM-DD_[video-title]/shorts/", "Share folder link in task comments"]},
        {"title": "Export Highlight Reel via Descript", "phase": "Repurposing", "day_offset": 11, "assignee_role": "operator", "description": "Create 1 highlight reel from the best moments. Used for collab post with RRG main account.", "checklist": ["Select best 3–5 moments from the full video", "Stitch into a single 60–90 second highlight reel", "Vertical 9:16 format", "Add animated captions", "Add RRG branding (this will be posted from RRG main account)", "Export as MP4", "Name file: highlight-reel.mp4", "Upload to Nextcloud: /videos/YYYY-MM-DD_[video-title]/highlight/", "Share link in task comments"]},

        # ── PHASE: Publishing Prep (Day 12–14) ──
        {"title": "Write 3 Title Variations", "phase": "Publishing Prep", "day_offset": 12, "assignee_role": "operator", "description": "Write 3 YouTube title variations for A/B testing.", "checklist": ["Title 1: Curiosity-based (open loop)", "Title 2: Outcome-based (result in title)", "Title 3: Authority/proof-based (number or claim)", "Each title under 60 characters", "Include primary keyword naturally", "No clickbait — must deliver on promise", "Log all 3 in the project notes or comments"]},
        {"title": "Write 3 Description Variations", "phase": "Publishing Prep", "day_offset": 12, "assignee_role": "operator", "description": "Write 3 YouTube description variations. First 2 lines must hook — they show before Read more.", "checklist": ["First 2 lines: what the video is about + who it's for", "Include VSL funnel link in first 100 characters", "Include lead magnet link as secondary CTA", "Timestamps for each section (paste from script)", "3–5 relevant hashtags at the bottom", "Write all 3 variations with different CTA framing", "Log all 3 in project notes or comments"]},
        {"title": "Create 3 Thumbnail Concepts", "phase": "Publishing Prep", "day_offset": 12, "assignee_role": "operator", "description": "Design 3 thumbnail variations for A/B testing. Bold, high-contrast, face-forward.", "checklist": ["Thumbnail 1: Vitto face + bold text overlay", "Thumbnail 2: Text-heavy, minimal face", "Thumbnail 3: Curiosity — question or partial reveal", "Size: 1280x720px, under 2MB", "Brand colours: red #A2182C, gold #97662D", "Font: bold, readable at small size", "No more than 6 words of text per thumbnail", "Export all 3 as JPG", "Upload to Nextcloud: /videos/YYYY-MM-DD_[video-title]/thumbnails/", "Share folder link in task comments"]},
        {"title": "Schedule Long-Form on YouTube", "phase": "Publishing Prep", "day_offset": 13, "assignee_role": "operator", "description": "Upload and schedule the long-form video on YouTube. Use Title 1 and Description 1 to start.", "checklist": ["Upload approved long-form MP4 to YouTube Studio", "Set title: use Variation 1 to start", "Paste description: use Variation 1", "Upload Thumbnail 1 as default", "Add to correct playlist", "Add all relevant tags and hashtags", "Set category: Education or People & Blogs", "Schedule for optimal time (Tue–Thu, 9–11AM EST)", "Set visibility: Scheduled (not public yet)", "Copy YouTube video link and paste in task comments"]},
        {"title": "Schedule 7 Shorts", "phase": "Publishing Prep", "day_offset": 13, "assignee_role": "operator", "description": "Schedule all 7 shorts across YouTube Shorts, Instagram Reels, and TikTok. Stagger over 10 days.", "checklist": ["Schedule Short 1: same day as long-form launch", "Schedule Short 2: Day +1", "Schedule Short 3: Day +2", "Schedule Short 4: Day +3", "Schedule Short 5: Day +5", "Schedule Short 6: Day +7", "Schedule Short 7: Day +10", "For each: write platform-specific caption with CTA to YouTube", "Upload to YouTube Shorts, Instagram Reels, TikTok", "Log all scheduled dates in task comments"]},
        {"title": "Schedule Highlight Reel + RRG Collab", "phase": "Publishing Prep", "day_offset": 13, "assignee_role": "operator", "description": "Schedule highlight reel as a collab post with RRG main account on Instagram.", "checklist": ["Upload highlight reel to Instagram from Vitto's account", "Tag RRG main account as collaborator", "Write caption: tie to the video topic, CTA to YouTube link in bio", "Add collab request — RRG account must accept", "Schedule for Day +1 after long-form goes live", "Confirm RRG account accepts collaboration", "Log scheduled date and collab status in comments"]},
        {"title": "Create 3 Stories to Drive YouTube Traffic", "phase": "Publishing Prep", "day_offset": 14, "assignee_role": "operator", "description": "Post 3 Instagram Stories leading viewers to the new YouTube video.", "checklist": ["Story 1: Teaser clip (15 sec from video) + link sticker to YouTube", "Story 2: Behind-the-scenes or context slide", "Story 3: Direct CTA — 'New video is live. Link in bio.'", "Add link sticker to each story pointing to YouTube video", "Post all 3 on launch day within 2 hours of video going live", "Pin the YouTube link to bio before stories go live", "Check story views at 24hr mark"]},

        # ── PHASE: Distribution (Day 14) ──
        {"title": "Set Up Distribution Links", "phase": "Distribution", "day_offset": 14, "assignee_role": "operator", "description": "Ensure all traffic from the video is funneled correctly. VSL first, lead magnet as secondary.", "checklist": ["Confirm VSL funnel link is live and working", "Confirm lead magnet link is live and working", "Update bio link to YouTube video", "Pin YouTube link in Instagram bio", "Update GHL — confirm no broken links", "Test VSL funnel from incognito browser", "Test lead magnet download from incognito browser", "Log all live links in task comments: YouTube, VSL, lead magnet"]},

        # ── PHASE: Analytics (Day 15, 21, 44) ──
        {"title": "24-Hour Analytics Check", "phase": "Analytics", "day_offset": 15, "assignee_role": "operator", "description": "First analytics pull at 24hrs post-launch. Check early signals.", "checklist": ["Open YouTube Studio → Analytics → select this video", "Log: Views", "Log: Impressions", "Log: CTR — benchmark: 4-8% is healthy", "Log: Average view duration — benchmark: 40%+ retention", "Log: Top traffic sources", "Check Shorts performance on each platform", "Check Instagram Story views and link taps", "Check VSL funnel traffic — any optins from video?", "Check lead magnet optins from video", "Log all numbers in project notes", "A/B test check: if CTR below 3%, swap to Title/Thumbnail 2"]},
        {"title": "7-Day Analytics Review", "phase": "Analytics", "day_offset": 21, "assignee_role": "operator", "description": "Full analytics review at 7 days. Make A/B test decisions. Check funnel conversion.", "checklist": ["Open YouTube Studio → Analytics → 7-day view", "Log: Total views", "Log: Watch time (hours)", "Log: Subscribers gained from this video", "Log: CTR (if still below 4%, swap to Title/Thumbnail 3)", "Log: Retention curve — where do people drop off?", "Log: Top comments — any content ideas surfaced?", "Check all 7 Shorts — which performed best?", "Check highlight reel collab — reach and engagement", "Check VSL funnel: total visits, optins, conversion rate", "Check lead magnet: total downloads/optins", "Identify best-performing short for paid promotion", "Log all numbers in project notes", "Flag any insights for next video topic"]},
        {"title": "30-Day Analytics Review & Feedback Loop", "phase": "Analytics", "day_offset": 44, "assignee_role": "operator", "description": "Final analytics pull at 30 days. Extract learnings and feed into next video cycle.", "checklist": ["Open YouTube Studio → Analytics → 28/30-day view", "Log: Total views", "Log: Total watch time", "Log: Subscribers gained", "Log: Revenue (if monetised)", "Log: Best-performing short", "Log: VSL funnel total conversions from this video", "Log: Lead magnet total conversions from this video", "Review comment section — recurring questions = next video topic", "Review DMs received referencing the video", "Final A/B test conclusion: which title/thumbnail/description won?", "Log winning combination for future videos", "Write 1-paragraph internal debrief: what worked, what to change", "Feed insights into next video script brief"]},
    ]
}

# ── Client Video — Full Production Pipeline ──
CLIENT_VIDEO_TEMPLATE = {
    "id": "rrm-client-video-production-v1",
    "is_global": True,
    "org_id": None,
    "name": "Client Video — Full Production Pipeline",
    "description": "End-to-end video production for an RRM media client. Client films themselves. RRM handles scripting, editing coordination, publishing setup, and analytics reporting. Covers script through 30-day analytics review.",
    "offer_type": "rrm_media_client",
    "type": "content",
    "trigger": None,
    "icon": "\U0001f3a5",
    "phases": [
        "Pre-Production",
        "Client Filming",
        "Post-Production",
        "Repurposing",
        "Publishing Prep",
        "Distribution",
        "Analytics & Reporting"
    ],
    "tasks": [
        # ── PHASE: Pre-Production (Day 0–3) ──
        {"title": "Define Video Topic & Angle", "phase": "Pre-Production", "day_offset": 0, "assignee_role": "account_manager", "is_client_visible": False, "description": "Lucca decides the topic and angle for this video based on the client's market, offer, and audience. Must align with their content strategy.", "checklist": ["Review client's ICP and offer (booked appointments for realtors)", "Choose a topic: market update / buyer tip / seller tip / agent story / proof", "Choose angle: educational / authority / behind-the-scenes / testimonial", "Confirm topic is not already covered in a recent video", "Log topic and angle decision in task comments"]},
        {"title": "Write Client Video Script", "phase": "Pre-Production", "day_offset": 1, "assignee_role": "operator", "is_client_visible": False, "description": "Write the full script in the CLIENT'S voice — not RRM's. Match their tone, market, and personality.", "checklist": ["Write in first person as the client (realtor)", "Hook: first 5 seconds must stop the scroll", "Body: one clear insight or story — no fluff", "CTA: book a call / visit their website / DM them — client's CTA, not RRM's", "Keep under 10 minutes for long-form; 60 seconds for short-form", "Format in Google Doc — label each section clearly", "Include b-roll notes (what to film besides talking head)", "Share Google Doc link in task comments"]},
        {"title": "Script Review & Approval", "phase": "Pre-Production", "day_offset": 2, "assignee_role": "account_manager", "is_client_visible": False, "description": "Vitto reviews the script for quality and alignment before sending to the client.", "checklist": ["Read full script", "Check it sounds like the client — not like RRM", "Check hook — would the client's audience stop scrolling?", "Check CTA — correct for this client's funnel", "Approve or leave revision notes in Google Doc", "Mark done only when approved"]},
        {"title": "Send Script to Client for Review", "phase": "Pre-Production", "day_offset": 2, "assignee_role": "operator", "is_client_visible": True, "description": "Send the approved script to the client. Give them 24–48hrs to review and approve before filming.", "checklist": ["Send Google Doc link via WhatsApp or email", "Tell client: read it out loud once before filming", "Tell client: suggest any changes to wording that feel unnatural", "Set 48hr deadline for client feedback", "Log date sent in task comments"]},
        {"title": "Incorporate Client Script Feedback", "phase": "Pre-Production", "day_offset": 3, "assignee_role": "operator", "is_client_visible": False, "description": "Apply any wording changes requested by the client. Keep the structure — only adjust phrasing.", "checklist": ["Review client's notes", "Apply phrasing changes that make it sound more natural for them", "Do NOT change the hook, structure, or CTA without Vitto approval", "Update Google Doc — mark as Final", "Notify client the script is final and ready to film"]},
        {"title": "Create Slide Assets (if needed)", "phase": "Pre-Production", "day_offset": 3, "assignee_role": "operator", "is_client_visible": False, "description": "Create any on-screen visuals, slides, or graphics needed for the video. Skip if not applicable.", "checklist": ["Identify script sections that need visual support", "Build slides using CLIENT'S branding — not RRM brand colours", "Use client's logo, colours, and fonts from their assets folder", "Export as PNG", "Upload to Nextcloud: ops.redribbongroup.ca — in client's folder", "Share Nextcloud folder link in task comments", "Mark N/A if no slides needed"]},
        {"title": "Send Client Filming Brief", "phase": "Pre-Production", "day_offset": 3, "assignee_role": "operator", "is_client_visible": True, "description": "Send the client a clear, simple filming brief. Most clients are not experienced on camera — make this foolproof.", "checklist": ["Send final script (Google Doc link)", "Send slide assets if applicable (Nextcloud link)", "Include filming instructions:", "  Film landscape (horizontal), not portrait", "  1080p or higher", "  Natural light facing them (window in front, not behind)", "  Clean background or branded background", "  Quiet room — no echo, no background noise", "  Film each section separately — easier to edit", "  Do multiple takes — do not delete anything", "  Upload ALL footage to Nextcloud link provided", "Create a Nextcloud upload folder for client: /clients/[client-name]/videos/YYYY-MM-DD/raw/", "Share upload link with client", "Set upload deadline: confirm with client (recommended 3–5 days)", "Send via WhatsApp with a voice note explanation if needed"]},

        # ── PHASE: Client Filming (Day 3–8) ──
        {"title": "Client Films Video", "phase": "Client Filming", "day_offset": 4, "assignee_role": "operator", "is_client_visible": True, "description": "Client films on their own. RRM is available for questions. Check in at 48hrs if no footage received.", "checklist": ["Confirm client received the filming brief", "Day 2 check-in: WhatsApp message — any questions on filming?", "Day 3 check-in if no upload: gentle nudge", "Confirm client uploads ALL footage to Nextcloud — not just the best take", "Do not proceed to editing until footage is confirmed in Nextcloud"]},
        {"title": "Confirm Footage Received on Nextcloud", "phase": "Client Filming", "day_offset": 8, "assignee_role": "operator", "is_client_visible": False, "description": "Log in to Nextcloud and confirm all client footage has been uploaded and is accessible.", "checklist": ["Log in to Nextcloud: https://ops.redribbongroup.ca/login?redirect_url=/apps/dashboard/", "Navigate to /clients/[client-name]/videos/YYYY-MM-DD/raw/", "Confirm footage files are present and playable", "Check file count — ask client if anything seems missing", "Download and spot-check 2–3 clips for audio and video quality", "If quality issues: send client specific re-filming instructions", "Log footage confirmation and file count in task comments"]},

        # ── PHASE: Post-Production (Day 8–16) ──
        {"title": "Send Editor Brief", "phase": "Post-Production", "day_offset": 8, "assignee_role": "operator", "is_client_visible": False, "description": "Package everything and brief the editor. The editor should not need to ask questions after receiving this.", "checklist": ["Share Nextcloud raw footage folder link", "Share Google Doc script link (final version)", "Share slide assets link if applicable", "Specify export format: landscape 16:9, MP4, H.264, 1080p", "Specify style: jump cuts, talking head, clean pacing", "Specify branding: use CLIENT's colours and logo — not RRM", "Specify captions: add auto-captions, review for accuracy", "Specify CTA: on-screen text at end = client's CTA from script", "Set deadline: agree with editor, log in comments", "Send via Conversations thread or WhatsApp"]},
        {"title": "Edit Long-Form Video", "phase": "Post-Production", "day_offset": 9, "assignee_role": "editor", "is_client_visible": False, "description": "Editor cuts the full video from client footage using the script as a guide.", "checklist": ["Import all footage from Nextcloud link", "Select best takes for each script section", "Cut to script — remove flubs, long pauses, repeated takes", "Add b-roll where script notes indicate", "Add slide assets at correct timestamps", "Add lower thirds: client name + title", "Colour grade — match client's brand aesthetic", "Add background music (royalty-free, very low volume)", "Add captions — auto-generate, then review for accuracy", "Add client logo watermark (corner, subtle)", "Export MP4 — 1080p, H.264", "Upload to Nextcloud: /clients/[client-name]/videos/YYYY-MM-DD/edit-v1/", "Share link in task comments"]},
        {"title": "RRM Internal Review (First Review)", "phase": "Post-Production", "day_offset": 13, "assignee_role": "account_manager", "is_client_visible": False, "description": "Vitto watches the edit before it goes to the client. Catch issues internally first.", "checklist": ["Watch full edit from Nextcloud link", "Check script adherence — did editor follow the structure?", "Check captions for accuracy", "Check branding — client logo, lower thirds correct?", "Check CTA segment — clear and long enough on screen?", "Check audio — no background noise, music not too loud", "Approve for client review OR send revision notes to editor", "Log decision in task comments"]},
        {"title": "Revision Round 1 — Internal (if needed)", "phase": "Post-Production", "day_offset": 14, "assignee_role": "editor", "is_client_visible": False, "description": "Apply internal revision notes before sending to client. Export as v2.", "checklist": ["Address all notes from internal review", "Export as edit-v2", "Upload to Nextcloud: /clients/[client-name]/videos/YYYY-MM-DD/edit-v2/", "Share link in task comments"]},
        {"title": "Send Edit to Client for Review", "phase": "Post-Production", "day_offset": 14, "assignee_role": "operator", "is_client_visible": True, "description": "Send the approved edit to the client for their review. Set clear expectations.", "checklist": ["Share Nextcloud link with client (view-only)", "Tell client: watch the full video once before giving feedback", "Tell client: feedback format — timestamp + specific note", "Tell client: max 2 rounds of revisions included", "Set 48hr deadline for client feedback", "Send via WhatsApp with context"]},
        {"title": "Client First Review", "phase": "Post-Production", "day_offset": 14, "assignee_role": "operator", "is_client_visible": True, "description": "Client watches the edit and provides feedback. RRM collects and filters revision notes.", "checklist": ["Client watches full edit", "Client logs feedback (timestamps + notes) in WhatsApp or Google Doc", "RRM review: are revision requests reasonable and within scope?", "Flag any out-of-scope requests (content changes = new script, not edit revision)", "Confirm revision list with editor", "Mark done when client feedback is received and triaged"]},
        {"title": "Revision Round 2 — Client Notes", "phase": "Post-Production", "day_offset": 15, "assignee_role": "editor", "is_client_visible": False, "description": "Apply client revision notes. Export as v3 — this should be the final version.", "checklist": ["Address all approved client revision notes", "Do NOT make changes not in the approved list", "Export as edit-v3 (final)", "Upload to Nextcloud: /clients/[client-name]/videos/YYYY-MM-DD/edit-final/", "Share link in task comments"]},
        {"title": "Client Final Approval", "phase": "Post-Production", "day_offset": 16, "assignee_role": "operator", "is_client_visible": True, "description": "Client gives final sign-off on the video. No further edits after this point.", "checklist": ["Share final edit (v3) Nextcloud link with client", "Get explicit approval in WhatsApp or email", "Do NOT proceed to repurposing without written approval", "Log approval confirmation in task comments", "Notify editor: final approved, no further changes"]},

        # ── PHASE: Repurposing (Day 16–19) ──
        {"title": "Export 7 Shorts via Descript", "phase": "Repurposing", "day_offset": 16, "assignee_role": "operator", "is_client_visible": False, "description": "Use Descript to clip 7 short-form videos from the approved final edit.", "checklist": ["Import approved final edit into Descript", "Identify 7 high-value clips from the video", "Each short: 30–90 seconds, vertical 9:16", "Add animated captions in Descript", "Add client logo watermark", "Export all 7 as MP4 — vertical 1080x1920", "Name files: [client-name]-short-01.mp4 through short-07.mp4", "Upload to Nextcloud: /clients/[client-name]/videos/YYYY-MM-DD/shorts/", "Share folder link in task comments"]},
        {"title": "Export Highlight Reel via Descript", "phase": "Repurposing", "day_offset": 17, "assignee_role": "operator", "is_client_visible": False, "description": "Create 1 highlight reel from the best moments. Client posts this from their own account.", "checklist": ["Select best 3–5 moments from the full video", "Stitch into a single 60–90 second highlight reel", "Vertical 9:16 format", "Add animated captions", "Add client branding (their logo, their colours)", "Export as MP4", "Name: [client-name]-highlight-reel.mp4", "Upload to Nextcloud: /clients/[client-name]/videos/YYYY-MM-DD/highlight/", "Share link in task comments"]},

        # ── PHASE: Publishing Prep (Day 18–21) ──
        {"title": "Write 3 Title Variations", "phase": "Publishing Prep", "day_offset": 18, "assignee_role": "operator", "is_client_visible": False, "description": "Write 3 YouTube title variations for A/B testing. Optimised for the client's local market and audience.", "checklist": ["Title 1: Curiosity-based (open loop)", "Title 2: Outcome-based (result or benefit in title)", "Title 3: Local market hook (mention city/area if relevant)", "Each under 60 characters", "Include primary keyword naturally", "Log all 3 in task comments"]},
        {"title": "Write 3 Description Variations", "phase": "Publishing Prep", "day_offset": 18, "assignee_role": "operator", "is_client_visible": False, "description": "Write 3 YouTube descriptions for A/B testing.", "checklist": ["First 2 lines: what the video covers + who it's for", "Include client's booking link or funnel in first 100 characters", "Include client's website as secondary link", "Add timestamps matching the script sections", "Add 3–5 relevant hashtags (local + niche)", "Write all 3 with different CTA framing", "Log all 3 in task comments"]},
        {"title": "Create 3 Thumbnail Concepts", "phase": "Publishing Prep", "day_offset": 18, "assignee_role": "operator", "is_client_visible": False, "description": "Design 3 thumbnail variations for A/B testing using the client's photo and branding.", "checklist": ["Thumbnail 1: Client face + bold text overlay", "Thumbnail 2: Text-heavy — question or bold claim", "Thumbnail 3: Local market hook — city name or property image", "Size: 1280x720px, under 2MB", "Use CLIENT's brand colours (from their assets)", "Client face must be clear and expressive", "No more than 6 words of text", "Export all 3 as JPG", "Upload to Nextcloud: /clients/[client-name]/videos/YYYY-MM-DD/thumbnails/", "Share folder link in task comments"]},
        {"title": "Send Publishing Assets to Client", "phase": "Publishing Prep", "day_offset": 19, "assignee_role": "operator", "is_client_visible": True, "description": "Package everything the client needs to publish — or publish on their behalf if they've given access.", "checklist": ["Confirm: does RRM have access to client's YouTube Studio?", "If YES — proceed to upload directly (next tasks)", "If NO — send client a publishing kit:", "  Final video MP4 (Nextcloud link)", "  3 title options (ask them to pick 1)", "  3 description options (ask them to pick 1)", "  3 thumbnail JPGs (ask them to pick 1)", "  Simple YouTube upload instructions", "  Shorts package (Nextcloud link)", "  Highlight reel (Nextcloud link)", "  Recommended posting schedule", "Log access status in task comments"]},
        {"title": "Schedule Long-Form on Client's YouTube", "phase": "Publishing Prep", "day_offset": 19, "assignee_role": "operator", "is_client_visible": False, "description": "Upload and schedule the long-form video on the client's YouTube channel.", "checklist": ["Upload approved final MP4 to client's YouTube Studio", "Set title: Variation 1 to start", "Paste description: Variation 1", "Upload Thumbnail 1 as default", "Add to correct playlist (create if needed)", "Add tags: client name, city, niche keywords", "Set category: Education or People & Blogs", "Schedule for optimal time (Tue–Thu, 9–11AM client's local time)", "Copy YouTube video URL and paste in task comments"]},
        {"title": "Schedule 7 Shorts on Client's Channels", "phase": "Publishing Prep", "day_offset": 20, "assignee_role": "operator", "is_client_visible": False, "description": "Schedule all 7 shorts across client's YouTube Shorts, Instagram Reels, and TikTok. Stagger over 10 days.", "checklist": ["Schedule Short 1: launch day", "Schedule Short 2: Day +1", "Schedule Short 3: Day +2", "Schedule Short 4: Day +3", "Schedule Short 5: Day +5", "Schedule Short 6: Day +7", "Schedule Short 7: Day +10", "For each short: write platform-specific caption with CTA", "Upload to YouTube Shorts, Instagram Reels, TikTok", "Confirm captions are visible and accurate on each platform", "Log all scheduled dates in task comments"]},
        {"title": "Schedule Highlight Reel on Client's Account", "phase": "Publishing Prep", "day_offset": 20, "assignee_role": "operator", "is_client_visible": False, "description": "Post highlight reel from client's Instagram account.", "checklist": ["Upload highlight reel to client's Instagram", "Write caption: tie to video topic, CTA to YouTube or booking link", "Schedule for Day +1 after long-form goes live", "Add relevant hashtags (local market + niche)", "Log scheduled date in task comments"]},
        {"title": "Create 3 Stories to Drive YouTube Traffic", "phase": "Publishing Prep", "day_offset": 21, "assignee_role": "operator", "is_client_visible": False, "description": "Post 3 Instagram Stories from the client's account on launch day to drive YouTube traffic.", "checklist": ["Story 1: Teaser clip (15 sec from video) + link sticker to YouTube", "Story 2: Context slide — what the video covers", "Story 3: Direct CTA — 'New video is live'", "Add link sticker on all 3 pointing to YouTube video", "Post all 3 on launch day within 2 hours of video going public", "Pin YouTube link to client's bio before stories go live", "Confirm with client before posting if they want to review Stories first"]},

        # ── PHASE: Distribution (Day 21) ──
        {"title": "Confirm Client Distribution Links Are Live", "phase": "Distribution", "day_offset": 21, "assignee_role": "operator", "is_client_visible": False, "description": "Verify all traffic from the video is funneled correctly to the client's booking system or funnel.", "checklist": ["Confirm client's booking link is live and working", "Confirm client's website or funnel link in description is correct", "Confirm bio link on Instagram points to YouTube video", "Test all links from incognito browser", "Confirm client's GHL pipeline is active (leads will come in)", "Log all live links in task comments: YouTube, booking link, bio link"]},

        # ── PHASE: Analytics & Reporting (Day 22, 28, 51) ──
        {"title": "24-Hour Analytics Check", "phase": "Analytics & Reporting", "day_offset": 22, "assignee_role": "operator", "is_client_visible": False, "description": "First analytics pull at 24hrs. Check early signals and flag anything unusual.", "checklist": ["Access client's YouTube Studio (confirm access is set up)", "Log: Views", "Log: Impressions", "Log: CTR — benchmark: 4-8% healthy. Below 3%: swap to Thumbnail 2", "Log: Average view duration — benchmark: 40%+ retention", "Log: Top traffic sources", "Check Shorts performance on each platform", "Check Instagram Story views and link taps", "Check client's booking link — any new leads or bookings from video?", "Flag anything unusual in task comments", "A/B decision: if CTR below 3%, swap title/thumbnail now"]},
        {"title": "7-Day Analytics Review & Client Report", "phase": "Analytics & Reporting", "day_offset": 28, "assignee_role": "operator", "is_client_visible": True, "description": "Full analytics review at 7 days. Send report to client. Make A/B test decisions.", "checklist": ["Pull YouTube Analytics — 7-day view", "Log: Total views", "Log: Watch time (hours)", "Log: Subscribers gained", "Log: CTR + retention curve", "Log: Top performing short", "Check client's booking system — leads attributed to video?", "Make A/B test decision: which title/thumbnail performing better?", "Swap to better performer if clear winner", "Prepare client report (keep it simple: views, watch time, top short, bookings)", "Send report to client via WhatsApp or email", "Log all numbers in task comments"]},
        {"title": "30-Day Analytics Review & Feedback Loop", "phase": "Analytics & Reporting", "day_offset": 51, "assignee_role": "operator", "is_client_visible": True, "description": "Final analytics pull at 30 days. Extract learnings, report to client, and feed into next video.", "checklist": ["Pull YouTube Analytics — 28/30-day view", "Log: Total views", "Log: Total watch time", "Log: Subscribers gained from this video", "Log: Best-performing short (consider boosting as paid ad)", "Log: Total bookings or leads attributed to this video", "Review comment section — any questions = next video topic", "Final A/B test conclusion: which combination won?", "Log winning title/thumbnail/description for future reference", "Write 1-paragraph debrief: what worked, what to change next time", "Send summary to client: how your video performed in 30 days", "Propose next video topic based on what resonated", "Feed insights into next script brief"]},
    ]
}

ALL_TEMPLATES = [
    RRM_MEDIA_CLIENT_TEMPLATE,
    CAMPAIGN_LAUNCH_TEMPLATE,
    VSL_FUNNEL_TEMPLATE,
    CREATIVE_REFRESH_TEMPLATE,
    OUTREACH_SPRINT_TEMPLATE,
    ISA_HIRE_TEMPLATE,
    YOUTUBE_VIDEO_TEMPLATE,
    CLIENT_VIDEO_TEMPLATE,
]
